server:
  port: 8761
  address: 127.0.0.1


spring:
  application:
    name: discoveryservice

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false